// apps/mobile/src/components/AnimatedAmount.tsx
// Живая сумма — порт web/src/components/AnimatedAmount.vue: каждый символ
// со стабильным ключом от правого края (единицы = d0), поэтому «555»→«5 555»
// не перемонтирует цифры — существующие глайдят, монтируется только новая
// левая. Ужатие при росте — scale контейнера, а не смена font-size.
import React, { useEffect } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import Animated, {
  Easing,
  LinearTransition,
  useAnimatedStyle,
  useSharedValue,
  withTiming,
  type EntryAnimationsValues,
  type ExitAnimationsValues,
} from 'react-native-reanimated';
import { font } from '@/theme/tokens';

const EASE_ZAP = Easing.bezier(0.32, 0.72, 0, 1);

// новая цифра: подъём + лёгкий скейл с пружинкой (.achar-enter)
const charEnter = (values: EntryAnimationsValues) => {
  'worklet';
  void values;
  return {
    initialValues: { opacity: 0, transform: [{ translateY: 6 }, { scale: 0.96 }] },
    animations: {
      opacity: withTiming(1, { duration: 180, easing: EASE_ZAP }),
      transform: [
        { translateY: withTiming(0, { duration: 180, easing: EASE_ZAP }) },
        { scale: withTiming(1, { duration: 180, easing: EASE_ZAP }) },
      ],
    },
  };
};

// удаление: быстрое затухание вниз (.achar-leave)
const charExit = (values: ExitAnimationsValues) => {
  'worklet';
  void values;
  return {
    initialValues: { opacity: 1, transform: [{ translateY: 0 }, { scale: 1 }] },
    animations: {
      opacity: withTiming(0, { duration: 140 }),
      transform: [
        { translateY: withTiming(6, { duration: 140 }) },
        { scale: withTiming(0.9, { duration: 140 }) },
      ],
    },
  };
};

interface Props {
  /** сырые цифры без разделителей ('' = zero-state) */
  digits: string;
  color: string;
  /** размер шрифта (масштаб-ужатие поверх него) */
  fontSize?: number;
}

export function AnimatedAmount({ digits, color, fontSize = 64 }: Props) {
  type Char = { key: string; ch: string; sep: boolean };
  const chars: Char[] = [];
  if (!digits) {
    chars.push({ key: 'zero', ch: '0', sep: false });
  } else {
    const n = digits.length;
    for (let r = n - 1; r >= 0; r--) {
      chars.push({ key: 'd' + r, ch: digits[n - 1 - r]!, sep: false });
      if (r > 0 && r % 3 === 0) chars.push({ key: 's' + r, ch: '', sep: true });
    }
  }

  // 64px-эквиваленты 52/44/38 через scale, как в вебе
  const len = chars.length;
  const target = len >= 11 ? 38 / 64 : len >= 9 ? 44 / 64 : len >= 7 ? 52 / 64 : 1;
  const scale = useSharedValue(target);
  useEffect(() => {
    scale.value = withTiming(target, { duration: 240, easing: EASE_ZAP });
  }, [target, scale]);
  const scaleStyle = useAnimatedStyle(() => ({ transform: [{ scale: scale.value }] }));

  const dim = !digits;

  return (
    <View style={[styles.line, { height: fontSize }]}>
      <Animated.View style={[styles.row, scaleStyle]}>
        {chars.map((c) => (
          <Animated.View
            key={c.key}
            entering={charEnter}
            exiting={charExit}
            layout={LinearTransition.duration(200).easing(EASE_ZAP)}
          >
            {c.sep ? (
              <View style={{ width: fontSize * 0.32 }} />
            ) : (
              <Text style={[styles.char, { fontSize, color, opacity: dim ? 0.35 : 1, lineHeight: fontSize * 1.06 }]}>
                {c.ch}
              </Text>
            )}
          </Animated.View>
        ))}
      </Animated.View>
    </View>
  );
}

const styles = StyleSheet.create({
  line: { alignItems: 'center', justifyContent: 'center', overflow: 'visible' },
  row: { flexDirection: 'row', alignItems: 'baseline' },
  char: { fontFamily: font.monoBold, letterSpacing: -1.28, fontVariant: ['tabular-nums'] },
});

// apps/web/src/components/AnimatedAmount.vue
<script setup lang="ts">
// Живая сумма: каждый символ — отдельный элемент со СТАБИЛЬНЫМ ключом от правого
// края (единицы = d0), поэтому «555»→«5 555» не перемонтирует цифры: существующие
// FLIP-глайдят на новые позиции, монтируется только новая левая. Ужатие при росте —
// scale контейнера, а не смена font-size.
import { computed } from 'vue'

const props = withDefaults(
  defineProps<{
    /** сырые цифры без разделителей ('' = zero-state) */
    digits: string
    /** приглушённый «0» при пустом вводе */
    placeholderZero?: boolean
    /** ужимать масштабом при 7/9/11 символах (для полноэкранного пада) */
    scaleSteps?: boolean
  }>(),
  { scaleSteps: true },
)

type Char = { key: string; ch: string; sep: boolean }

const chars = computed<Char[]>(() => {
  const d = props.digits
  if (!d) return [{ key: 'zero', ch: '0', sep: false }]
  const n = d.length
  const out: Char[] = []
  // слева направо: цифра с right-index r; после цифры с r%3===0 (r>0) — разделитель s{r}
  for (let r = n - 1; r >= 0; r--) {
    out.push({ key: 'd' + r, ch: d[n - 1 - r]!, sep: false })
    if (r > 0 && r % 3 === 0) out.push({ key: 's' + r, ch: '', sep: true })
  }
  return out
})

// 64px-эквиваленты 52/44/38 через transform: scale
const scale = computed(() => {
  if (!props.scaleSteps) return 1
  const len = chars.value.length
  if (len >= 11) return 38 / 64
  if (len >= 9) return 44 / 64
  if (len >= 7) return 52 / 64
  return 1
})

const dim = computed(() => props.placeholderZero && !props.digits)

/** до absolute фиксируем ширину — соседи глайдят на освободившееся место */
function beforeLeave(el: Element) {
  const e = el as HTMLElement
  e.style.width = e.offsetWidth + 'px'
  e.style.left = e.offsetLeft + 'px'
  e.style.top = e.offsetTop + 'px'
}
</script>

<template>
  <!-- фиксированная высота строки: масштаб не двигает контент ниже -->
  <div class="flex items-center justify-center overflow-visible" style="height: 1em">
    <span
      class="amount-scale inline-flex items-baseline whitespace-nowrap tabular-nums transition-colors duration-150 [font-variant-numeric:tabular-nums]"
      :class="dim ? 'text-ink/35' : ''"
      :style="{ transform: `scale(${scale})` }"
    >
      <TransitionGroup name="achar" @before-leave="beforeLeave">
        <span v-for="c in chars" :key="c.key" class="achar relative inline-block">
          <template v-if="c.sep"><span class="inline-block" style="width: 0.32em" /></template>
          <template v-else>{{ c.ch }}</template>
        </span>
      </TransitionGroup>
    </span>
  </div>
</template>

<style>
.amount-scale {
  transform-origin: center;
  transition: transform 240ms cubic-bezier(0.32, 0.72, 0, 1);
  position: relative;
}
/* новая цифра: подъём + лёгкий скейл с пружинкой */
.achar-enter-active {
  transition:
    opacity 200ms cubic-bezier(0.34, 1.4, 0.5, 1),
    transform 200ms cubic-bezier(0.34, 1.4, 0.5, 1);
}
.achar-enter-from {
  opacity: 0;
  transform: translateY(10px) scale(0.9);
}
/* удаление: absolute (ширина зафиксирована хуком) — соседи глайдят */
.achar-leave-active {
  transition:
    opacity 140ms ease,
    transform 140ms ease;
  position: absolute;
  pointer-events: none;
}
.achar-leave-to {
  opacity: 0;
  transform: translateY(6px) scale(0.9);
}
/* FLIP: перегруппировка «555»→«5 555» едет, а не прыгает */
.achar-move {
  transition: transform 240ms cubic-bezier(0.32, 0.72, 0, 1);
}
@media (prefers-reduced-motion: reduce) {
  .amount-scale {
    transition: none;
  }
  .achar-enter-active,
  .achar-leave-active {
    transition: opacity 100ms ease !important;
  }
  .achar-enter-from,
  .achar-leave-to {
    transform: none !important;
  }
  .achar-move {
    transition: none !important;
  }
}
</style>
