// apps/mobile/src/components/CountUp.tsx
// Каунт-ап суммы, как CountUp.vue: цифры бегут к значению с ease-out.
// rAF на JS достаточно — обновляется текст, вёрстка не трогается.
import React, { useEffect, useRef, useState } from 'react';
import { Text, type StyleProp, type TextStyle } from 'react-native';
import { money } from '@/lib/format';

interface Props {
  value: number;
  duration?: number;
  prefix?: string;
  style?: StyleProp<TextStyle>;
}

export function CountUp({ value, duration = 800, prefix = '', style }: Props) {
  // как в вебе: на маунте бежим 0 -> value
  const [shown, setShown] = useState(0);
  const from = useRef(0);

  useEffect(() => {
    const start = from.current;
    if (start === value) return;
    const t0 = Date.now();
    let raf: number;
    const tick = () => {
      const k = Math.min(1, (Date.now() - t0) / duration);
      const e = 1 - Math.pow(1 - k, 3); // easeOutCubic
      setShown(Math.round(start + (value - start) * e));
      if (k < 1) raf = requestAnimationFrame(tick);
      else from.current = value;
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [value, duration]);

  return (
    <Text style={[{ fontVariant: ['tabular-nums'] }, style]} numberOfLines={1}>
      {prefix}
      {money(shown)}
    </Text>
  );
}

// apps/web/src/components/CountUp.vue
<script setup lang="ts">
import { computed, onMounted, ref, watch } from 'vue'
import { money } from '@/lib/format'

const props = withDefaults(
  defineProps<{
    value: number
    duration?: number
    prefix?: string
    autostart?: boolean
  }>(),
  // важно: отсутствующий boolean-проп Vue приводит к false, поэтому явный default
  { autostart: true },
)

const current = ref(0)
let raf = 0

const reduced =
  typeof window !== 'undefined' && window.matchMedia('(prefers-reduced-motion: reduce)').matches

function animate(to: number) {
  cancelAnimationFrame(raf)
  if (reduced) {
    current.value = to
    return
  }
  const from = current.value
  const dur = props.duration ?? 1100
  const start = performance.now()
  const step = (now: number) => {
    const t = Math.min(1, (now - start) / dur)
    const eased = 1 - Math.pow(1 - t, 3)
    current.value = Math.round(from + (to - from) * eased)
    if (t < 1) raf = requestAnimationFrame(step)
  }
  raf = requestAnimationFrame(step)
}

onMounted(() => {
  if (props.autostart) animate(props.value)
})

watch(
  () => props.value,
  (v) => animate(v),
)

const text = computed(() => (props.prefix ?? '') + money(current.value))
</script>

<template>
  <span class="tabular-nums">{{ text }}</span>
</template>
