// apps/mobile/src/components/FunStatCards.tsx
// Смешная статистика компании как игровые ачивки.
//
// Сетка 2×2 без прокрутки (требование руководства: всё должно помещаться в
// экран). Плитка — стикер, значение, подпись; тон ироничный (§C11), это не
// лидерборд.
import React from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { STICKER } from '@/components/EmptyState';
import type { FunStat } from '@/lib/funStats';
import { money } from '@/lib/format';
import { useTheme } from '@/theme/ThemeProvider';
import { font } from '@/theme/tokens';

/** фирменные стикеры вместо эмодзи — по замечанию руководства */
const ART: Record<FunStat['kind'], keyof typeof STICKER> = {
  fastest: 'paidDone',
  alwaysLast: 'receiptHero',
  biggest: 'themeFood',
  buddy: 'fistBump',
  bigWallet: 'wallet',
  smallWallet: 'oneBill',
  alwaysBroke: 'billDone',
};

interface Props {
  fun: FunStat[];
  nameOf: (contactId: string) => string;
}

export function FunStatCards({ fun, nameOf }: Props) {
  const { t } = useTranslation();
  const { colors } = useTheme();
  if (!fun.length) return null;

  /* значение плитки: у «быстрее всех» и «вечно последний» — человек, у
     «самого крупного» — сумма; так подпись читается без второй строки */
  const value = (s: FunStat): string => {
    if (s.kind === 'biggest') return money(s.value);
    return nameOf(s.contactId ?? '') || '—';
  };

  return (
    <View style={styles.grid}>
      {fun.map((s) => (
        <View key={s.kind} style={[styles.card, { backgroundColor: colors.shell }]}>
          <Image source={STICKER[ART[s.kind]]} style={styles.art} resizeMode="contain" />
          <View style={styles.body}>
            <Text style={[styles.value, { color: colors.ink }]} numberOfLines={1} adjustsFontSizeToFit>
              {value(s)}
            </Text>
            <Text style={[styles.label, { color: colors.muted }]} numberOfLines={1}>
              {t(`crew.card${s.kind.charAt(0).toUpperCase()}${s.kind.slice(1)}`)}
            </Text>
          </View>
        </View>
      ))}
    </View>
  );
}

const styles = StyleSheet.create({
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 14 },
  // без тени: крупная мягкая тень выглядела тяжело
  card: { flexGrow: 1, flexBasis: '47%', borderRadius: 18, paddingVertical: 11, paddingHorizontal: 12, flexDirection: 'row', alignItems: 'center', gap: 10 },
  art: { width: 38, height: 34 },
  body: { flex: 1, minWidth: 0 },
  value: { fontFamily: font.extrabold, fontSize: 15, letterSpacing: -0.3 },
  label: { fontFamily: font.semibold, fontSize: 10.5, marginTop: 4, lineHeight: 15 },
});

// apps/web/src/components/FunStatCards.vue
<script setup lang="ts">
/*
  Смешная статистика компании как игровые ачивки: сетка 2×2 без прокрутки —
  всё помещается в экран. Тон ироничный (vision §C11), это не лидерборд.
*/
import { useI18n } from 'vue-i18n'
import { money } from '@/lib/format'
import type { FunStat } from '@/lib/funStats'

const props = defineProps<{
  fun: FunStat[]
  nameOf: (contactId: string) => string
}>()

const { t } = useI18n()

const GLYPH: Record<FunStat['kind'], string> = {
  fastest: '⚡',
  alwaysLast: '👀',
  biggest: '🍕',
  buddy: '🤝',
  bigWallet: '💸',
  smallWallet: '🪙',
  alwaysBroke: '🫠',
}

function value(s: FunStat): string {
  if (s.kind === 'biggest') return money(s.value)
  return props.nameOf(s.contactId ?? '') || '—'
}

function label(s: FunStat): string {
  return t(`crew.card${s.kind.charAt(0).toUpperCase()}${s.kind.slice(1)}`)
}
</script>

<template>
  <div v-if="props.fun.length" class="grid grid-cols-2 gap-2.5">
    <div
      v-for="s in props.fun"
      :key="s.kind"
      class="flex items-center gap-2.5 rounded-[18px] bg-shell px-3 py-2.5"
    >
      <span class="text-[22px]">{{ GLYPH[s.kind] }}</span>
      <div class="min-w-0">
        <p class="truncate text-[15px] font-extrabold tracking-[-0.01em]">{{ value(s) }}</p>
        <p class="truncate text-[10.5px] font-semibold text-muted">{{ label(s) }}</p>
      </div>
    </div>
  </div>
</template>
