// apps/mobile/src/components/MerchantCashbackSlider.tsx
// Кэшбэк по заведениям — свайп-карточки вверху экрана.
//
// Требование руководства: сверху 2–3 заведения (Bellissimo, EVOS, Feed Up),
// листаются пальцем, минимализм — «супер-эпп для молодых». Первая карточка —
// «все» с общим балансом, дальше по заведению: сколько накопилось именно там.
//
// Прокрутка с привязкой к карточке (snapToInterval), под лентой — точки.
//
// Карточка не должна быть «цифрой в прямоугольнике»: у общей — точечный узор
// и стикер-кошелёк, у заведений — крупный полупрозрачный знак категории
// фоном, лаймовый процент и строка «за N сплитов». Это витрина, а не отчёт.
import React, { useMemo, useState } from 'react';
import {
  Image,
  ScrollView,
  StyleSheet,
  Text,
  View,
  useWindowDimensions,
  type NativeScrollEvent,
  type NativeSyntheticEvent,
} from 'react-native';
import { useTranslation } from 'react-i18next';
import Svg, { Defs, Pattern, Circle as SvgCircle, Rect as SvgRect } from 'react-native-svg';
import { CountUp } from '@/components/CountUp';
import { STICKER } from '@/components/EmptyState';
import type { CashbackEntry } from '@zap/shared/types';
import { money } from '@/lib/format';
import { merchantGlyph, merchantLogo } from '@/lib/merchantLogo';
import { useTheme } from '@/theme/ThemeProvider';
import { SCREEN_PAD_X, font } from '@/theme/tokens';

const GAP = 10;

interface Props {
  entries: CashbackEntry[];
  total: number;
}

export function MerchantCashbackSlider({ entries, total }: Props) {
  const { t } = useTranslation();
  const { colors, fixed } = useTheme();
  const { width } = useWindowDimensions();
  const [page, setPage] = useState(0);

  // карточка чуть уже экрана — край следующей виден, и понятно, что листается
  const CARD_W = width - SCREEN_PAD_X * 2 - 34;
  const STEP = CARD_W + GAP;

  const byMerchant = useMemo(() => {
    const acc = new Map<string, { title: string; amount: number; count: number; badge: string }>();
    for (const e of entries) {
      const cur = acc.get(e.title) ?? { title: e.title, amount: 0, count: 0, badge: e.badge };
      cur.amount += e.amount;
      cur.count += 1;
      acc.set(e.title, cur);
    }
    return [...acc.values()].sort((a, b) => b.amount - a.amount).slice(0, 4);
  }, [entries]);

  const onScroll = (ev: NativeSyntheticEvent<NativeScrollEvent>) => {
    setPage(Math.round(ev.nativeEvent.contentOffset.x / STEP));
  };

  const pages = 1 + byMerchant.length;

  return (
    <View>
      <ScrollView
        horizontal
        showsHorizontalScrollIndicator={false}
        decelerationRate="fast"
        snapToInterval={STEP}
        snapToAlignment="start"
        onScroll={onScroll}
        scrollEventThrottle={16}
        style={styles.strip}
        contentContainerStyle={styles.stripBody}
      >
        {/* общая — лаймовая витрина с узором и стикером */}
        <View style={[styles.card, { width: CARD_W, backgroundColor: fixed.lime }]}>
          <Svg style={StyleSheet.absoluteFill} width="100%" height="100%">
            <Defs>
              <Pattern id="cbDots" width={14} height={14} patternUnits="userSpaceOnUse">
                <SvgCircle cx={2} cy={2} r={1.4} fill="rgba(17,17,16,0.16)" />
              </Pattern>
            </Defs>
            <SvgRect x={0} y={0} width="100%" height="100%" fill="url(#cbDots)" />
          </Svg>
          <Image source={STICKER.wallet} style={styles.totalArt} resizeMode="contain" />
          <Text style={styles.kicker}>{t('cashback.available')}</Text>
          <CountUp value={total} duration={800} style={styles.bigValue} />
          <Text style={styles.cardFoot}>{t('cashback.allPlaces')}</Text>
        </View>

        {byMerchant.map((m) => (
          <View key={m.title} style={[styles.card, { width: CARD_W, backgroundColor: colors.shell }]}>
            {/* знак категории фоном — карточка узнаётся боковым зрением */}
            <Text style={styles.ghost} pointerEvents="none">{merchantGlyph(m.title)}</Text>
            <View style={styles.cardHead}>
              {merchantLogo(m.title) ? (
                <Image source={merchantLogo(m.title)!} style={styles.logo} />
              ) : (
                <View style={[styles.logo, styles.logoLetter, { backgroundColor: colors.sand }]}>
                  <Text style={styles.logoLetterText}>{merchantGlyph(m.title)}</Text>
                </View>
              )}
              <View style={[styles.pct, { backgroundColor: fixed.lime }]}>
                <Text style={styles.pctText}>{m.badge.split(' · ')[0]}</Text>
              </View>
            </View>
            <Text style={[styles.value, { color: colors.ink }]} numberOfLines={1} adjustsFontSizeToFit>
              {money(m.amount)}
            </Text>
            <View style={styles.cardFootRow}>
              <Text style={[styles.cardFootDim, { color: colors.ink }]} numberOfLines={1}>
                {m.title}
              </Text>
              <Text style={[styles.cardCount, { color: colors.faint }]} numberOfLines={1}>
                {t('cashback.fromSplits', { n: m.count })}
              </Text>
            </View>
          </View>
        ))}
      </ScrollView>

      {pages > 1 ? (
        <View style={styles.dots}>
          {Array.from({ length: pages }).map((_, i) => (
            <View
              key={i}
              style={[
                styles.dot,
                { backgroundColor: i === page ? colors.ink : colors.sand2 },
                i === page && styles.dotActive,
              ]}
            />
          ))}
        </View>
      ) : null}
    </View>
  );
}

const styles = StyleSheet.create({
  strip: { marginHorizontal: -SCREEN_PAD_X },
  stripBody: { paddingHorizontal: SCREEN_PAD_X, gap: GAP },
  card: { borderRadius: 24, padding: 18, minHeight: 148, justifyContent: 'space-between', overflow: 'hidden' },
  totalArt: { position: 'absolute', right: -8, top: 6, width: 96, height: 82, transform: [{ rotate: '10deg' }] },
  ghost: { position: 'absolute', right: -6, bottom: -18, fontSize: 96, opacity: 0.07 },
  cardFootRow: { marginTop: 4 },
  cardCount: { fontFamily: font.semibold, fontSize: 11, marginTop: 1 },
  cardHead: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  logo: { width: 44, height: 44, borderRadius: 14 },
  logoLetter: { alignItems: 'center', justifyContent: 'center' },
  logoLetterText: { fontFamily: font.extrabold, fontSize: 17 },
  pct: { height: 26, paddingHorizontal: 11, borderRadius: 999, justifyContent: 'center' },
  pctText: { fontFamily: font.extrabold, fontSize: 11.5, color: '#111110' },
  kicker: { fontFamily: font.monoBold, fontSize: 9.5, letterSpacing: 1.5, color: 'rgba(17,17,16,0.55)' },
  bigValue: { fontFamily: font.extrabold, fontSize: 38, letterSpacing: -1.2, color: '#111110', marginTop: 4 },
  value: { fontFamily: font.extrabold, fontSize: 30, letterSpacing: -0.9, marginTop: 12 },
  cardFoot: { fontFamily: font.bold, fontSize: 12, color: 'rgba(17,17,16,0.55)', marginTop: 6 },
  cardFootDim: { fontFamily: font.extrabold, fontSize: 13.5, letterSpacing: -0.2 },
  dots: { flexDirection: 'row', gap: 5, justifyContent: 'center', marginTop: 12 },
  dot: { width: 6, height: 6, borderRadius: 999 },
  dotActive: { width: 16 },
});

// apps/web/src/components/MerchantCashbackSlider.vue
<script setup lang="ts">
/*
  Кэшбэк по заведениям — свайп-карточки вверху экрана: общая сумма, дальше по
  местам. Карточка чуть уже экрана, край следующей виден — понятно, что
  листается. Это витрина, а не отчёт: узор, стикер-кошелёк и знак категории
  фоном.
*/
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import CountUp from '@/components/CountUp.vue'
import VenueIcon from '@/components/VenueIcon.vue'
import { money } from '@/lib/format'
import { merchantGlyph } from '@/lib/merchantLogo'
import type { CashbackEntry } from '@zap/shared/types'

const props = defineProps<{ entries: CashbackEntry[]; total: number }>()
const { t } = useI18n()

const page = ref(0)

const byMerchant = computed(() => {
  const acc = new Map<string, { title: string; amount: number; count: number; badge: string }>()
  for (const e of props.entries) {
    const cur = acc.get(e.title) ?? { title: e.title, amount: 0, count: 0, badge: e.badge }
    cur.amount += e.amount
    cur.count += 1
    acc.set(e.title, cur)
  }
  return [...acc.values()].sort((a, b) => b.amount - a.amount).slice(0, 4)
})

function onScroll(ev: Event) {
  const el = ev.target as HTMLElement
  page.value = Math.round(el.scrollLeft / (el.clientWidth * 0.88))
}
</script>

<template>
  <div>
    <div
      class="no-scrollbar -mx-6 mt-[18px] flex snap-x snap-mandatory gap-2.5 overflow-x-auto px-6"
      @scroll="onScroll"
    >
      <div class="w-[86%] shrink-0 snap-start rounded-[24px] bg-lime p-[18px] text-on-lime">
        <p class="font-mono text-[9.5px] font-bold tracking-[0.15em] opacity-60">{{ t('cashback.available') }}</p>
        <CountUp :value="props.total" :duration="800" class="mt-1 block text-[38px] font-extrabold leading-none tracking-[-0.03em]" />
        <p class="mt-1.5 text-[12px] font-bold opacity-60">{{ t('cashback.allPlaces') }}</p>
      </div>

      <div
        v-for="m in byMerchant"
        :key="m.title"
        class="relative w-[86%] shrink-0 snap-start overflow-hidden rounded-[24px] bg-shell p-[18px]"
      >
        <span class="pointer-events-none absolute -bottom-5 -right-2 text-[96px] opacity-[0.07]">{{ merchantGlyph(m.title) }}</span>
        <div class="flex items-center justify-between">
          <VenueIcon :name="m.title" size="md" />
          <span class="flex h-[26px] items-center rounded-full bg-lime px-[11px] text-[11.5px] font-extrabold text-on-lime">
            {{ m.badge.split(' · ')[0] }}
          </span>
        </div>
        <p class="mt-3 text-[30px] font-extrabold leading-none tracking-[-0.03em]">{{ money(m.amount) }}</p>
        <p class="mt-1 text-[13.5px] font-extrabold">{{ m.title }}</p>
        <p class="text-[11px] font-semibold text-faint">{{ t('cashback.fromSplits', { n: m.count }) }}</p>
      </div>
    </div>

    <div v-if="byMerchant.length" class="mt-3 flex justify-center gap-1.5">
      <span
        v-for="i in byMerchant.length + 1"
        :key="i"
        class="h-1.5 rounded-full transition-all"
        :class="i - 1 === page ? 'w-4 bg-ink' : 'w-1.5 bg-sand-2'"
      />
    </div>
  </div>
</template>
