// apps/web/src/components/ActiveSplitPill.vue
<script setup lang="ts">
// Дизайн 4a: чёрная плашка активного сплита над таб-баром —
// логотип мерчанта, «Активный сплит», «ждём Бека · 128 000», лаймовый прогресс.
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useSplitsStore } from '@/entities/stores/splits'
import { useContactsStore } from '@/entities/stores/contacts'
import { useUserStore } from '@/entities/stores/user'
import { money } from '@/lib/format'
import bellissimoLogo from '@/assets/brand/partners/bellissimo.png'
import { useI18n } from 'vue-i18n'

const route = useRoute()
const router = useRouter()
const { t } = useI18n()
const splits = useSplitsStore()
const contacts = useContactsStore()
const user = useUserStore()

const split = computed(() => splits.activeSplit)

// только на главной: на пэде суммы плашка перекрывала «Далее»
const show = computed(() => user.isAuthed && route.path === '/' && split.value !== null)

const waitingNames = computed(() => {
  if (!split.value) return ''
  const names = split.value.members
    .filter((m) => m.status === 'waiting' || m.status === 'opened')
    .map((m) => contacts.byId(m.contactId)?.name ?? '?')
  if (!names.length) return ''
  
  return names.join(t('common.and'))
})

const remaining = computed(() =>
  (split.value?.members ?? [])
    .filter((m) => m.status !== 'paid' && m.status !== 'debt')
    .reduce((s, m) => s + m.amount, 0),
)

const progress = computed(() => {
  if (!split.value) return 0
  const paid = split.value.members
    .filter((m) => m.status === 'paid' || m.status === 'debt')
    .reduce((s, m) => s + m.amount, 0)
  return Math.round((paid / split.value.total) * 100)
})

const isBellissimo = computed(() => split.value?.merchantId === 'm_bellissimo')
const merchant = computed(() => contacts.merchantById(split.value?.merchantId))
</script>

<template>
  <Transition name="pill">
    <button
      v-if="show && split"
      type="button"
      class="press fixed bottom-[calc(86px+env(safe-area-inset-bottom))] left-1/2 z-30 flex w-[calc(100%-28px)] max-w-[374px] -translate-x-1/2 items-center gap-3 rounded-full bg-ink py-[13px] pl-[11px] pr-[18px] text-left shadow-[0_14px_34px_rgba(30,28,16,0.35)]"
      @click="router.push(`/split/${split.id}`)"
    >
      <img v-if="isBellissimo" :src="bellissimoLogo" alt="" class="merchant-img h-[42px] w-[42px] rounded-full object-cover" />
      <div
        v-else
        class="flex h-[42px] w-[42px] items-center justify-center rounded-full text-[16px] font-extrabold text-paper"
        :style="{ background: merchant?.color ?? '#3E3C35' }"
      >
        {{ merchant?.letter ?? split.title[0]?.toUpperCase() }}
      </div>
      <div class="min-w-0 flex-1 space-y-[7px]">
        <div class="flex items-baseline justify-between gap-2">
          <span class="whitespace-nowrap text-[14.5px] font-extrabold text-paper">{{ t('home.activeSplit') }}</span>
          <span class="truncate text-[12px] font-bold text-paper/55">
            <template v-if="waitingNames">{{ t('home.waitingFor', { names: waitingNames, amount: money(remaining) }) }}</template>
            <template v-else>{{ t('home.allPaid') }}</template>
          </span>
        </div>
        <div class="h-[6px] overflow-hidden rounded-full bg-white/[0.18]">
          <div class="h-full w-full origin-left rounded-full bg-lime transition-transform duration-500 ease-zap" :style="{ transform: `scaleX(${progress / 100})` }" />
        </div>
      </div>
      <span class="text-[17px] font-semibold text-paper/50">›</span>
    </button>
  </Transition>
</template>

// apps/mobile/src/components/ActiveSplitPill.tsx
// Плашка активного сплита над таб-баром — порт ActiveSplitPill.vue:
// круг мерчанта (лого Bellissimo или буква на цвете), «Активный сплит» +
// «ждём … · сумма» справа, лаймовый прогресс-бар 6px.
import React, { useEffect } from 'react';
import { Image, StyleSheet, Text, View } from 'react-native';
import Animated, { Easing, FadeInDown, FadeOutDown, useAnimatedStyle, useSharedValue, withTiming } from 'react-native-reanimated';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useTranslation } from 'react-i18next';
import { PressableScale } from '@/components/PressableScale';
import { useTheme } from '@/theme/ThemeProvider';
import { font } from '@/theme/tokens';
import { money } from '@/lib/format';
import type { Merchant, Split } from '@zap/shared/types';

interface Props {
  split: Split;
  merchant?: Merchant;
  nameOf: (contactId: string) => string;
  onPress: () => void;
}

export function ActiveSplitPill({ split, merchant, nameOf, onPress }: Props) {
  const { t } = useTranslation();
  const { fixed } = useTheme();
  const insets = useSafeAreaInsets();

  const waitingNames = split.members
    .filter((m) => m.status === 'waiting' || m.status === 'opened')
    .map((m) => nameOf(m.contactId))
    .filter(Boolean);
  const remaining = split.members
    .filter((m) => m.status !== 'paid' && m.status !== 'debt')
    .reduce((s, m) => s + m.amount, 0);
  const paid = split.members
    .filter((m) => m.status === 'paid' || m.status === 'debt')
    .reduce((s, m) => s + m.amount, 0);
  const progress = split.total > 0 ? Math.min(1, paid / split.total) : 0;

  const label = waitingNames.length
    ? t('home.waitingFor', { names: waitingNames.join(t('common.and')), amount: money(remaining) })
    : t('home.allPaid');

  // прогресс подъезжает за 500 мс — как transition в вебе
  const p = useSharedValue(progress);
  useEffect(() => {
    p.value = withTiming(progress, { duration: 500, easing: Easing.bezier(0.32, 0.72, 0, 1) });
  }, [progress, p]);
  const barStyle = useAnimatedStyle(() => ({ width: `${p.value * 100}%` }));

  const isBellissimo = split.merchantId === 'm_bellissimo';

  return (
    <Animated.View
      entering={FadeInDown.duration(320)}
      exiting={FadeOutDown.duration(180)}
      // над таб-баром: его высота 62 + отступ 14 + безопасная зона
      style={[styles.wrap, { bottom: insets.bottom + 90 }]}
      pointerEvents="box-none"
    >
      <PressableScale style={[styles.pill, { backgroundColor: fixed.ink }]} onPress={onPress}>
        {isBellissimo ? (
          <Image source={require('../../assets/brand/partners/bellissimo.png')} style={styles.logo} />
        ) : (
          <View style={[styles.logo, { backgroundColor: merchant?.color ?? '#3E3C35', alignItems: 'center', justifyContent: 'center' }]}>
            <Text style={[styles.logoLetter, { color: fixed.paper }]}>
              {merchant?.letter ?? split.title[0]?.toUpperCase()}
            </Text>
          </View>
        )}
        <View style={styles.body}>
          <View style={styles.titleRow}>
            <Text style={[styles.title, { color: fixed.paper }]} numberOfLines={1}>
              {t('home.activeSplit')}
            </Text>
            <Text style={[styles.sub, { color: fixed.paper }]} numberOfLines={1}>
              {label}
            </Text>
          </View>
          <View style={styles.track}>
            <Animated.View style={[styles.bar, { backgroundColor: fixed.lime }, barStyle]} />
          </View>
        </View>
        <Text style={[styles.chevron, { color: fixed.paper }]}>›</Text>
      </PressableScale>
    </Animated.View>
  );
}

const styles = StyleSheet.create({
  wrap: { position: 'absolute', left: 14, right: 14, alignItems: 'center' },
  pill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    alignSelf: 'stretch',
    maxWidth: 374,
    paddingVertical: 13,
    paddingLeft: 11,
    paddingRight: 18,
    borderRadius: 999,
    shadowColor: '#1E1C10',
    shadowOpacity: 0.35,
    shadowRadius: 34,
    shadowOffset: { width: 0, height: 14 },
    elevation: 10,
  },
  logo: { width: 42, height: 42, borderRadius: 999 },
  logoLetter: { fontFamily: font.extrabold, fontSize: 16 },
  body: { flex: 1, minWidth: 0, gap: 7 },
  titleRow: { flexDirection: 'row', alignItems: 'baseline', justifyContent: 'space-between', gap: 8 },
  title: { fontFamily: font.extrabold, fontSize: 14.5 },
  sub: { flexShrink: 1, fontFamily: font.bold, fontSize: 12, opacity: 0.55 },
  track: { height: 6, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.18)', overflow: 'hidden' },
  bar: { height: '100%', borderRadius: 999 },
  chevron: { fontFamily: font.semibold, fontSize: 17, opacity: 0.5 },
});
