// apps/web/src/components/PlayerCard.vue
<script setup lang="ts">
/*
  Карточка игрока — шапка профиля, как в приложении: аватар по центру, слева
  уровень и сплиты, справа компании и кэшбэк, ниже полоса опыта до следующего
  ранга. Профиль перестаёт быть «просто аккаунтом».

  Ранг считается от числа сплитов: единственная метрика, которая растёт от
  использования продукта и не зависит от денег.
*/
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { myPersona } from '@/lib/personas'

const props = defineProps<{
  name: string
  handle: string
  since: string
  splits: number
  cashback: string
  groups: number
}>()

const emit = defineEmits<{ (e: 'pick'): void }>()

const { t } = useI18n()

const RANKS = [0, 5, 15, 30, 60, 120]

const level = computed(() => {
  let l = 0
  RANKS.forEach((v, i) => {
    if (props.splits >= v) l = i
  })
  return l
})
const from = computed(() => RANKS[level.value]!)
const next = computed<number | null>(() => RANKS[level.value + 1] ?? null)
const progress = computed(() =>
  next.value ? Math.min(1, (props.splits - from.value) / (next.value - from.value)) : 1,
)
</script>

<template>
  <div class="rounded-[26px] bg-shell p-[18px]">
    <div class="flex items-center justify-between">
      <div class="w-[82px] text-center">
        <p class="font-mono text-[8.5px] font-bold uppercase tracking-[0.12em] text-faint-2">{{ t('profile.level') }}</p>
        <p class="mt-0.5 text-[19px] font-extrabold tracking-[-0.02em]">✦ {{ level + 1 }}</p>
        <p class="mt-3.5 font-mono text-[8.5px] font-bold uppercase tracking-[0.12em] text-faint-2">{{ t('profile.statSplitsUnit') }}</p>
        <p class="mt-0.5 text-[19px] font-extrabold tracking-[-0.02em]">{{ props.splits }}</p>
      </div>

      <button type="button" class="press relative" @click="emit('pick')">
        <img :src="myPersona()" alt="" class="h-[104px] w-[104px] rounded-full ring-[3.5px] ring-lime" />
        <span class="absolute -bottom-0.5 -left-1 grid h-[30px] min-w-[30px] place-items-center rounded-full border-[3px] border-shell bg-ink px-1.5 text-[13px] font-extrabold text-lime">
          {{ level + 1 }}
        </span>
        <span class="absolute -bottom-0.5 -right-0.5 grid h-7 w-7 place-items-center rounded-full border-[3px] border-shell bg-lime text-[12px] text-on-lime">✎</span>
      </button>

      <div class="w-[82px] text-center">
        <p class="font-mono text-[8.5px] font-bold uppercase tracking-[0.12em] text-faint-2">{{ t('profile.statGroupsUnit') }}</p>
        <p class="mt-0.5 text-[19px] font-extrabold tracking-[-0.02em]">{{ props.groups }}</p>
        <p class="mt-3.5 font-mono text-[8.5px] font-bold uppercase tracking-[0.12em] text-faint-2">{{ t('profile.statCashbackUnit') }}</p>
        <p class="mt-0.5 truncate text-[15px] font-extrabold tracking-[-0.02em]">{{ props.cashback }}</p>
      </div>
    </div>

    <div class="mt-3 flex flex-col items-center gap-[3px]">
      <h1 class="text-[22px] font-extrabold tracking-[-0.02em]">{{ props.name }}</h1>
      <p class="text-[13px] font-semibold text-muted">{{ props.handle }} · {{ props.since }}</p>
      <span class="mt-1 flex h-[26px] items-center rounded-full bg-lime px-[11px] text-[12px] font-extrabold tracking-[0.01em] text-on-lime">
        {{ t(`profile.rank${level}`) }}
      </span>
    </div>

    <div class="mt-[18px]">
      <div class="mb-[7px] flex items-baseline justify-between gap-2">
        <span class="text-[12px] font-semibold text-muted">
          {{ next ? t('profile.toNextRank', { n: next - props.splits, rank: t(`profile.rank${level + 1}`) }) : t('profile.maxRank') }}
        </span>
        <span class="text-[12px] font-extrabold">{{ next ? `${props.splits}/${next}` : props.splits }}</span>
      </div>
      <div class="h-2.5 overflow-hidden rounded-full bg-sand">
        <div class="h-full rounded-full bg-lime transition-[width] duration-500" :style="{ width: `${Math.max(6, progress * 100)}%` }" />
      </div>
    </div>
  </div>
</template>

// apps/mobile/src/components/PlayerCard.tsx
// Карточка игрока — шапка профиля (vision V2 §C1, слой Duolingo).
//
// Профиль был «просто аккаунт»: аватар, имя, телефон. Здесь он читается как
// профиль в игре — ранг, полоса опыта до следующего ранга и три показателя
// одной строкой. Светлая: тёмную шапку руководство отклонило.
//
// Ранг считается от числа сплитов: это единственная метрика, которая растёт
// от использования продукта и не зависит от денег.
import React from 'react';
import { Image, StyleSheet, Text, View, type ImageSourcePropType } from 'react-native';
import Animated, { FadeIn } from 'react-native-reanimated';
import { useTranslation } from 'react-i18next';
import { PressableScale } from '@/components/PressableScale';
import { useTheme } from '@/theme/ThemeProvider';
import { font } from '@/theme/tokens';

/** пороги рангов: индекс = уровень, значение = сплитов для входа */
const RANKS = [0, 5, 15, 30, 60, 120] as const;

export function rankOf(splits: number): { level: number; from: number; next: number | null } {
  let level = 0;
  for (let i = 0; i < RANKS.length; i++) if (splits >= RANKS[i]!) level = i;
  return { level, from: RANKS[level]!, next: RANKS[level + 1] ?? null };
}

interface Props {
  avatar: ImageSourcePropType | null;
  initials: string;
  name: string;
  handle: string;
  /** «в ZAP! с августа» — короткой строкой под ником */
  since: string;
  splits: number;
  cashback: string;
  groups: number;
  onAvatarPress: () => void;
}

export function PlayerCard({ avatar, initials, name, handle, since, splits, cashback, groups, onAvatarPress }: Props) {
  const { t } = useTranslation();
  const { colors, fixed } = useTheme();
  const { level, from, next } = rankOf(splits);
  const progress = next ? Math.min(1, (splits - from) / (next - from)) : 1;

  return (
    <Animated.View entering={FadeIn.duration(260)} style={[styles.card, { backgroundColor: colors.shell }]}>
      {/*
        Аватар по центру, показатели по бокам — как в присланном образце
        игрового профиля: слева уровень, справа число сплитов.
      */}
      <View style={styles.top}>
        <View style={styles.side}>
          <Stat label={t('profile.level')} value={`✦ ${level + 1}`} />
          <Stat label={t('profile.statSplitsUnit')} value={String(splits)} />
        </View>

        <PressableScale haptic={false} onPress={onAvatarPress}>
          <View style={[styles.avatarWrap, { borderColor: fixed.lime }]}>
            {avatar ? (
              <Image source={avatar} style={styles.avatar} />
            ) : (
              <View style={[styles.avatar, styles.fallback, { backgroundColor: colors.ink }]}>
                <Text style={[styles.fallbackText, { color: fixed.lime }]}>{initials}</Text>
              </View>
            )}
            {/* уровень — как шеврон на аватаре в играх */}
            <View style={[styles.levelBadge, { backgroundColor: colors.ink, borderColor: colors.shell }]}>
              <Text style={[styles.levelText, { color: fixed.lime }]}>{level + 1}</Text>
            </View>
            <View style={[styles.editDot, { backgroundColor: fixed.lime, borderColor: colors.shell }]}>
              <Text style={styles.editGlyph}>✎</Text>
            </View>
          </View>
        </PressableScale>

        <View style={styles.side}>
          <Stat label={t('profile.statGroupsUnit')} value={String(groups)} />
          <Stat label={t('profile.statCashbackUnit')} value={cashback} />
        </View>
      </View>

      <View style={styles.who}>
        <Text style={[styles.name, { color: colors.ink }]} numberOfLines={1}>{name}</Text>
        <Text style={[styles.handle, { color: colors.muted }]} numberOfLines={1}>
          {handle} · {since}
        </Text>
        <View style={[styles.rankChip, { backgroundColor: fixed.lime }]}>
          <Text style={styles.rankText} numberOfLines={1}>{t(`profile.rank${level}`)}</Text>
        </View>
      </View>

      {/* полоса опыта до следующего ранга */}
      <View style={styles.xpBlock}>
        <View style={styles.xpLabels}>
          <Text style={[styles.xpText, { color: colors.muted }]}>
            {next ? t('profile.toNextRank', { n: next - splits, rank: t(`profile.rank${level + 1}`) }) : t('profile.maxRank')}
          </Text>
          <Text style={[styles.xpCount, { color: colors.ink }]}>{next ? `${splits}/${next}` : `${splits}`}</Text>
        </View>
        <View style={[styles.track, { backgroundColor: colors.sand }]}>
          <View style={[styles.bar, { backgroundColor: fixed.lime, width: `${Math.max(6, progress * 100)}%` }]} />
        </View>
      </View>

    </Animated.View>
  );
}

/** Показатель у края карточки: подпись мелким моно, значение жирным. */
function Stat({ label, value }: { label: string; value: string }) {
  const { colors } = useTheme();
  return (
    <View style={styles.stat}>
      <Text style={[styles.sideLabel, { color: colors.faint2 }]} numberOfLines={1}>{label}</Text>
      <Text style={[styles.sideValue, { color: colors.ink }]} numberOfLines={1} adjustsFontSizeToFit>
        {value}
      </Text>
    </View>
  );
}

const styles = StyleSheet.create({
  card: { borderRadius: 26, padding: 18, marginTop: 4, overflow: 'hidden' },
  top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  side: { width: 82, alignItems: 'center', gap: 14 },
  stat: { alignItems: 'center', alignSelf: 'stretch' },
  sideLabel: { fontFamily: font.monoBold, fontSize: 8.5, letterSpacing: 1.1, textTransform: 'uppercase' },
  sideValue: { fontFamily: font.extrabold, fontSize: 19, letterSpacing: -0.4, marginTop: 3 },
  avatarWrap: { width: 104, height: 104, borderRadius: 999, borderWidth: 3.5 },
  avatar: { width: '100%', height: '100%', borderRadius: 999 },
  fallback: { alignItems: 'center', justifyContent: 'center' },
  fallbackText: { fontFamily: font.extrabold, fontSize: 34 },
  levelBadge: {
    position: 'absolute',
    left: -4,
    bottom: -2,
    minWidth: 30,
    height: 30,
    paddingHorizontal: 6,
    borderRadius: 999,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  levelText: { fontFamily: font.extrabold, fontSize: 13 },
  editDot: {
    position: 'absolute',
    right: -2,
    bottom: -2,
    width: 28,
    height: 28,
    borderRadius: 999,
    borderWidth: 3,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editGlyph: { fontSize: 12, color: '#121212' },
  who: { alignItems: 'center', gap: 3, marginTop: 12 },
  name: { fontFamily: font.extrabold, fontSize: 22, letterSpacing: -0.4 },
  handle: { fontFamily: font.semibold, fontSize: 13 },
  rankChip: { alignSelf: 'center', marginTop: 5, height: 26, paddingHorizontal: 11, borderRadius: 999, justifyContent: 'center' },
  rankText: { fontFamily: font.extrabold, fontSize: 12, color: '#121212', letterSpacing: 0.2 },
  xpBlock: { marginTop: 18 },
  xpLabels: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'baseline', marginBottom: 7 },
  xpText: { fontFamily: font.semibold, fontSize: 12, flex: 1, marginRight: 8 },
  xpCount: { fontFamily: font.extrabold, fontSize: 12 },
  track: { height: 10, borderRadius: 999, overflow: 'hidden' },
  bar: { height: '100%', borderRadius: 999 },
});
